# Generated by Django 5.1.7 on 2025-06-30 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0002_alter_commande_statut_detailcommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepenseRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPENSE', 'Dépense'), ('REVENU', 'Revenu')], max_length=7)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_financiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
