# Generated by Django 5.1.7 on 2025-06-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0003_alerte_depenserevenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricole.produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='MouvementFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('DEPENSE', 'Dépense'), ('REVENU', 'Revenu')], max_length=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
