# Generated by Django 5.1.7 on 2025-07-03 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0005_materiel_alter_produit_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmateriel',
            options={},
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reservationmateriel',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='alerte',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerte',
            name='lue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reservationmateriel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationmateriel',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricole.materiel'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('approuve', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
