# Generated by Django 5.1.7 on 2025-07-22 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0006_alter_reservationmateriel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'Client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
