# Generated by Django 5.1.7 on 2025-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0007_alter_commande_client_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
