# Generated by Django 5.1.7 on 2025-08-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0009_service_alter_reservationmateriel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True),
        ),
    ]
