# Generated by Django 5.1.7 on 2025-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0011_produit_image_static'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image_static',
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, help_text="Classe d'icône (ex: 'fas fa-bell')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Urgent'), ('primary', 'Primaire')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, help_text='URL de redirection lors du clic sur la notification', null=True),
        ),
    ]
