# Generated by Django 5.1.7 on 2025-09-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0012_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_static',
            field=models.CharField(blank=True, help_text="Chemin relatif dans static, ex: 'dist/img/sorgho.jpg'", max_length=255, null=True),
        ),
    ]
