# Generated by Django 5.1.7 on 2025-10-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0013_produit_image_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_attente_paiement', 'En attente de paiement'), ('payee', 'Payée'), ('paiement_echoue', 'Paiement échoué'), ('validee', 'Validée et traitée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='payment_method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('a_la_livraison', 'Paiement à la livraison')], default='a_la_livraison', max_length=50),
        ),
    ]
