# Generated by Django 5.1.5 on 2025-12-12 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0015_alter_client_options_client_city_client_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['nom'], 'verbose_name': 'Culture', 'verbose_name_plural': 'Cultures'},
        ),
        migrations.RemoveField(
            model_name='culture',
            name='date_recolte',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='date_semis',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='superficie',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='culture',
            name='besoins_eau',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Besoins en eau'),
        ),
        migrations.AddField(
            model_name='culture',
            name='besoins_nutriments',
            field=models.TextField(blank=True, null=True, verbose_name='Besoins en nutriments'),
        ),
        migrations.AddField(
            model_name='culture',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='culture',
            name='duree_cycle',
            field=models.PositiveIntegerField(default=90, help_text='Durée du cycle en jours', verbose_name='Durée du cycle (jours)'),
        ),
        migrations.AddField(
            model_name='culture',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Culture active'),
        ),
        migrations.AddField(
            model_name='culture',
            name='periode_semis_optimale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Période de semis optimale'),
        ),
        migrations.AddField(
            model_name='culture',
            name='rendement_moyen',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rendement moyen en tonnes/hectare', max_digits=6, verbose_name='Rendement moyen (t/ha)'),
        ),
        migrations.AddField(
            model_name='culture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_attente_paiement', 'En attente de paiement'), ('payee', 'Payée'), ('paiement_echoue', 'Paiement échoué'), ('validee', 'Validée et traitée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='culture',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='type_culture',
            field=models.CharField(choices=[('mais', 'Maïs'), ('riz', 'Riz'), ('oignon', 'Oignon'), ('mil', 'Mil'), ('arachide', 'Arachide'), ('sorgho', 'Sorgho'), ('tomate', 'Tomate'), ('poivron', 'Poivron'), ('aubergine', 'Aubergine'), ('carotte', 'Carotte'), ('chou', 'Chou'), ('autre', 'Autre')], max_length=20, verbose_name='Type de culture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('3', 'Client'), ('4', 'Agriculteur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ADMIN'), ('4', 'AGRICULTEUR'), ('3', 'CLIENT')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'En attente'), ('Validated', 'Validé'), ('Rejected', 'Rejeté'), ('Refunded', 'Remboursé')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la parcelle')),
                ('code_unique', models.CharField(max_length=50, unique=True, verbose_name='Code unique de la parcelle')),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en hectares', max_digits=8, verbose_name='Superficie (ha)')),
                ('localisation', models.CharField(max_length=255, verbose_name='Localisation')),
                ('coordonnees_gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordonnées GPS')),
                ('type_sol', models.CharField(choices=[('argileux', 'Argileux'), ('limoneux', 'Limoneux'), ('sableux', 'Sableux'), ('calcaire', 'Calcaire'), ('humifere', 'Humifère'), ('autre', 'Autre')], max_length=20, verbose_name='Type de sol')),
                ('ph_sol', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH du sol')),
                ('qualite_eau', models.CharField(blank=True, max_length=100, null=True, verbose_name="Qualité de l'eau")),
                ('systeme_irrigation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Système d'irrigation")),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('en_preparation', 'En préparation'), ('en_repos', 'En repos'), ('maintenance', 'En maintenance')], default='disponible', max_length=20, verbose_name='Statut')),
                ('date_assignation', models.DateField(blank=True, null=True, verbose_name="Date d'assignation")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('est_active', models.BooleanField(default=True, verbose_name='Parcelle active')),
                ('agriculteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agricole.agriculteur', verbose_name='Agriculteur assigné')),
                ('culture_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agricole.culture', verbose_name='Culture actuelle')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ItineraireTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('preparation_sol', 'Préparation du sol'), ('semis', 'Semis'), ('fertilisation', 'Fertilisation'), ('irrigation', 'Irrigation'), ('desherbage', 'Désherbage'), ('traitement_phytosanitaire', 'Traitement phytosanitaire'), ('recolte', 'Récolte'), ('post_recolte', 'Post-récolte')], max_length=30)),
                ('description', models.TextField(verbose_name="Description de l'étape")),
                ('date_planifiee', models.DateField(verbose_name='Date planifiée')),
                ('date_realisee', models.DateField(blank=True, null=True, verbose_name='Date réalisée')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('realise', 'Réalisé'), ('retard', 'Retard'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricole.culture')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to='agricole.parcelle')),
            ],
            options={
                'verbose_name': 'Itinéraire technique',
                'verbose_name_plural': 'Itinéraires techniques',
                'ordering': ['date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('semis', 'Semis'), ('traitement', 'Traitement'), ('irrigation', 'Irrigation'), ('fertilisation', 'Fertilisation'), ('recolte', 'Récolte'), ('surveillance', 'Surveillance'), ('maintenance', 'Maintenance'), ('autre', 'Autre')], max_length=20)),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('date_planifiee', models.DateTimeField(verbose_name='Date planifiée')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('en_attente_validation', 'En attente de validation')], default='planifie', max_length=25)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricole.agriculteur', verbose_name='Agriculteur')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricole.culture')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='agricole.parcelle')),
            ],
            options={
                'verbose_name': 'Activité agricole',
                'verbose_name_plural': 'Activités agricoles',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
