# Generated by Django 5.1.5 on 2025-12-12 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0016_alter_culture_options_remove_culture_date_recolte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiel',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Matériel agricole', 'verbose_name_plural': 'Matériels agricoles'},
        ),
        migrations.AlterModelOptions(
            name='reservationmateriel',
            options={'ordering': ['-date_reservation'], 'verbose_name': 'Réservation de matériel', 'verbose_name_plural': 'Réservations de matériel'},
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='prix_location',
        ),
        migrations.AddField(
            model_name='materiel',
            name='annee_fabrication',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de fabrication'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiel',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de série'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='prix_location_jour',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Prix de location par jour (FCFA)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiel',
            name='quantite_disponible',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité disponible'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='quantite_totale',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité totale'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('maintenance', 'En maintenance'), ('reserve', 'Réservé')], default='disponible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='commentaire_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='date_debut_reelle',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début réelle'),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='date_fin_reelle',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin réelle'),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='prix_jour_applique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par jour appliqué'),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='prix_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total'),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('en_cours', 'En cours de location'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='reservationmateriel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='categorie',
            field=models.CharField(choices=[('tracteur', 'Tracteur'), ('moissonneuse', 'Moissonneuse-batteuse'), ('pulverisateur', 'Pulvérisateur'), ('semoir', 'Semoir'), ('charrue', 'Charrue'), ('herse', 'Herse'), ('irrigation', "Matériel d'irrigation"), ('recolte', 'Matériel de récolte'), ('transport', 'Matériel de transport'), ('autre', 'Autre')], max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible à la location'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom du matériel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materiels/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='reservationmateriel',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='reservationmateriel',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='reservationmateriel',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='reservationmateriel',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation'),
        ),
        migrations.AlterField(
            model_name='reservationmateriel',
            name='validee',
            field=models.BooleanField(default=False, verbose_name='Validée'),
        ),
    ]
