# Generated by Django 5.1.5 on 2025-12-12 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0017_alter_materiel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contenu', models.TextField(help_text='Contenu détaillé de la fiche-conseil')),
                ('recommandations', models.TextField(help_text='Recommandations principales')),
                ('periode_optimale', models.CharField(help_text="Période optimale pour l'application", max_length=100)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyenne', 'Moyenne'), ('difficile', 'Difficile')], default='moyenne', max_length=20)),
                ('type_culture', models.CharField(choices=[('cereales', 'Céréales'), ('legumes', 'Légumes'), ('fruits', 'Fruits'), ('racines', 'Racines et tubercules'), ('legumineuses', 'Légumineuses'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('categorie', models.CharField(choices=[('plantation', 'Plantation'), ('entretien', 'Entretien'), ('recolte', 'Récolte'), ('traitement', 'Traitement'), ('fertilisation', 'Fertilisation'), ('irrigation', 'Irrigation'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fiches_conseils/')),
                ('publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('telechargements', models.PositiveIntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_conseils', to=settings.AUTH_USER_MODEL)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_conseils', to='agricole.culture')),
            ],
            options={
                'verbose_name': 'Fiche-conseil',
                'verbose_name_plural': 'Fiches-conseils',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_cultures/')),
                ('description', models.TextField(blank=True, help_text='Description de la photo')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire du technicien')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='agricole.agriculteur')),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='agricole.culture')),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='agricole.parcelle')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo de culture',
                'verbose_name_plural': 'Photos de cultures',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
