# Generated by Django 5.1.5 on 2025-12-12 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0018_ficheconseil_photoculture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#007bff', help_text='Code couleur hexadécimal', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#28a745', help_text='Code couleur hexadécimal', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie de revenu',
                'verbose_name_plural': 'Catégories de revenus',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la dépense')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date_depense', models.DateField(verbose_name='Date de la dépense')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('fournisseur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fournisseur')),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de facture')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_depenses/', verbose_name='Pièce jointe')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='validee', max_length=20, verbose_name='Statut')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agricole.categoriedepense', verbose_name='Catégorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_reglement', models.DateField(blank=True, null=True, verbose_name='Date de règlement')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant réglé')),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant restant')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée'), ('en_retard', 'En retard')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(verbose_name='Description des services/produits')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/', verbose_name='Fichier PDF')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricole.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(verbose_name='Date du paiement')),
                ('methode_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('mtn_momo', 'MTN Mobile Money'), ('carte_bancaire', 'Carte bancaire'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire')], max_length=50, verbose_name='Méthode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence du paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='valide', max_length=20, verbose_name='Statut')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricole.client', verbose_name='Client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='agricole.facture')),
            ],
            options={
                'verbose_name': 'Paiement client',
                'verbose_name_plural': 'Paiements clients',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('mensuel', 'Rapport mensuel'), ('trimestriel', 'Rapport trimestriel'), ('annuel', 'Rapport annuel'), ('personnalise', 'Rapport personnalisé')], max_length=50, verbose_name='Type de rapport')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('periode_debut', models.DateField(verbose_name='Début de la période')),
                ('periode_fin', models.DateField(verbose_name='Fin de la période')),
                ('total_depenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports_financiers/pdf/')),
                ('fichier_excel', models.FileField(blank=True, null=True, upload_to='rapports_financiers/excel/')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport financier',
                'verbose_name_plural': 'Rapports financiers',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du revenu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date_revenu', models.DateField(verbose_name='Date du revenu')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('client', models.CharField(blank=True, max_length=200, null=True, verbose_name='Client/Source')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_revenus/', verbose_name='Pièce jointe')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='validee', max_length=20, verbose_name='Statut')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agricole.categorierevenu', verbose_name='Catégorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenu',
                'verbose_name_plural': 'Revenus',
                'ordering': ['-date_revenu'],
            },
        ),
        migrations.CreateModel(
            name='SoldeMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('mois', models.IntegerField(verbose_name='Mois (1-12)')),
                ('total_depenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total dépenses')),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total revenus')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde net')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solde mensuel',
                'verbose_name_plural': 'Soldes mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('utilisateur', 'annee', 'mois')},
            },
        ),
    ]
