# Generated by Django 5.1.5 on 2025-12-13 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0019_categoriedepense_categorierevenu_depense_facture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date'], 'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['produit__nom_produit']},
        ),
        migrations.AddField(
            model_name='commande',
            name='gérant',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_gererees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='reference',
            field=models.CharField(blank=True, help_text="Référence de la commande ou de l'opération", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('utilisateur', 'produit')},
        ),
    ]
