# Generated by Django 4.2.27 on 2026-02-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricole', '0020_alter_mouvementstock_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_attente_paiement', 'En attente de paiement'), ('payee_en_attente', 'Payée - En attente de validation gérant'), ('paiement_echoue', 'Paiement échoué'), ('validee', 'Validée et traitée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
